name = "push-notification-cf-worker"
main = "src/worker.ts"
compatibility_date = "2023-08-14"

compatibility_flags = [ "nodejs_compat" ] # for node:async_hooks

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[env.production]

d1_databases = [
  { binding = "DB", database_name = "push-notification-db", database_id = "df3f9e4f-4835-45c8-88ef-af9050637b11" }
]

[triggers]
crons = ["* * * * *", "*/1 * * * *", "*/2 * * * *"]
